# Generated by Django 4.2.7 on 2023-12-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('three_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('rfc', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('three_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lot', models.CharField(max_length=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('generic', models.BooleanField(default=False)),
                ('administration', models.CharField(max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Provideer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('second_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('product_sold', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=40)),
                ('cp', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('sale_hour', models.TimeField(auto_now_add=True)),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_store.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_store.product')),
            ],
        ),
        migrations.CreateModel(
            name='RemessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], default='tarjeta', max_length=10)),
                ('hour_order', models.TimeField(auto_now_add=True)),
                ('day_order', models.DateField(auto_now_add=True)),
                ('hour_delivery', models.TimeField()),
                ('day_delivery', models.DateField()),
                ('subtotal', models.IntegerField()),
                ('amout', models.IntegerField()),
                ('provideer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_store.provideer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_purchased', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drug_store.saledetails')),
                ('rfc_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_store.client')),
            ],
        ),
    ]
