# Generated by Django 4.2.7 on 2023-12-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='products_purchased',
        ),
        migrations.AddField(
            model_name='bill',
            name='products_purchased',
            field=models.ManyToManyField(to='drug_store.saledetails'),
        ),
    ]
