# Generated by Django 4.2.7 on 2023-12-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0002_remove_bill_products_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prescription',
            field=models.BooleanField(default=False),
        ),
    ]
