# Generated by Django 4.2.7 on 2023-12-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0003_product_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_type',
            field=models.CharField(choices=[('oral', 'Oral'), ('instramuscular', 'Intramuscular'), ('intravenosa', 'Intravenosa'), ('sublingual', 'Sublingual')], default='tarjeta', max_length=20),
        ),
        migrations.RemoveField(
            model_name='saledetails',
            name='product',
        ),
        migrations.AddField(
            model_name='saledetails',
            name='product',
            field=models.ManyToManyField(to='drug_store.product'),
        ),
    ]
