# Generated by Django 4.2.7 on 2023-12-06 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0004_product_payment_type_remove_saledetails_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemissionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], default='tarjeta', max_length=10, verbose_name='Tipo de Pago')),
                ('hour_order', models.TimeField(auto_now_add=True, verbose_name='Hora de Orden')),
                ('day_order', models.DateField(auto_now_add=True, verbose_name='Fecha de Orden')),
                ('hour_delivery', models.TimeField(verbose_name='Hora de Entrega')),
                ('day_delivery', models.DateField(verbose_name='Fecha de Entrega')),
                ('subtotal', models.IntegerField(verbose_name='Subtotal')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='payment_type',
        ),
        migrations.AlterField(
            model_name='bill',
            name='products_purchased',
            field=models.ManyToManyField(to='drug_store.saledetails', verbose_name='Detalles de Venta'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rfc_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_store.client', verbose_name='Cliente RFC'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(max_length=13, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_name',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='client',
            name='three_name',
            field=models.CharField(max_length=50, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='second_name',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='three_name',
            field=models.CharField(max_length=50, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='product',
            name='administration',
            field=models.CharField(choices=[('oral', 'Oral'), ('intramuscular', 'Intramuscular'), ('intravenosa', 'Intravenosa'), ('sublingual', 'Sublingual')], default='oral', max_length=30, verbose_name='Administración'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(verbose_name='Fecha de Caducidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='generic',
            field=models.BooleanField(default=False, verbose_name='Genérico'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lot',
            field=models.CharField(max_length=10, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prescription',
            field=models.BooleanField(default=False, verbose_name='Prescripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='provideer',
            name='cp',
            field=models.CharField(max_length=5, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='provideer',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provideer',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='provideer',
            name='product_sold',
            field=models.CharField(max_length=30, verbose_name='Producto Vendido'),
        ),
        migrations.AlterField(
            model_name='provideer',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='provideer',
            name='state',
            field=models.CharField(max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='provideer',
            name='street',
            field=models.CharField(max_length=40, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_store.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='product',
            field=models.ManyToManyField(to='drug_store.product', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad Vendida'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='sale_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='sale_hour',
            field=models.TimeField(auto_now_add=True, verbose_name='Hora de Venta'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.DeleteModel(
            name='RemessionNote',
        ),
        migrations.AddField(
            model_name='remissionnote',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug_store.provideer', verbose_name='Proveedor'),
        ),
    ]
