# Generated by Django 4.2.7 on 2023-12-06 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0006_alter_bill_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remissionnote',
            options={'verbose_name_plural': 'Pedidos Proveedores'},
        ),
    ]
