# Generated by Django 4.2.7 on 2023-12-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0010_alter_provideer_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provideer',
            name='product_sold',
        ),
        migrations.AddField(
            model_name='provideer',
            name='product_sold',
            field=models.ManyToManyField(to='drug_store.product', verbose_name='Producto'),
        ),
    ]
