# Generated by Django 4.2.7 on 2023-12-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0011_remove_provideer_product_sold_provideer_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='remissionnote',
            name='products',
            field=models.ManyToManyField(to='drug_store.product', verbose_name='Productos'),
        ),
    ]
