# Generated by Django 4.2.7 on 2023-12-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0012_product_stock_remissionnote_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remissionnote',
            name='day_order',
            field=models.DateField(verbose_name='Fecha de Orden'),
        ),
        migrations.AlterField(
            model_name='remissionnote',
            name='hour_order',
            field=models.TimeField(verbose_name='Hora de Orden'),
        ),
    ]
