# Generated by Django 4.2.7 on 2023-12-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0013_alter_remissionnote_day_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remissionnote',
            name='products',
        ),
        migrations.AlterField(
            model_name='remissionnote',
            name='day_order',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Orden'),
        ),
        migrations.AlterField(
            model_name='remissionnote',
            name='hour_order',
            field=models.TimeField(auto_now_add=True, verbose_name='Hora de Orden'),
        ),
    ]
