# Generated by Django 4.2.7 on 2023-12-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0014_remove_remissionnote_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remissionnote',
            name='_has_been_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remissionnote',
            name='products',
            field=models.ManyToManyField(to='drug_store.product', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='remissionnote',
            name='day_order',
            field=models.DateField(verbose_name='Fecha de Orden'),
        ),
        migrations.AlterField(
            model_name='remissionnote',
            name='hour_order',
            field=models.TimeField(verbose_name='Hora de Orden'),
        ),
    ]
