# Generated by Django 4.2.7 on 2023-12-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0015_remissionnote__has_been_saved_remissionnote_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remissionnote',
            name='_has_been_saved',
        ),
    ]
