# Generated by Django 4.2.7 on 2023-12-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0016_remove_remissionnote__has_been_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remissionnote',
            name='products',
        ),
    ]
