# Generated by Django 4.2.7 on 2023-12-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug_store', '0017_remove_remissionnote_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='remission_note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drug_store.remissionnote'),
            preserve_default=False,
        ),
    ]
